import type { Design, Designer } from '../types';

export const DESIGNERS: Designer[] = [
  {
    id: 'd1',
    name: 'Chukwudi Adesanya',
    initials: 'CA',
    location: 'Lagos',
    totalDesigns: 38,
    rating: 4.9,
    reviewCount: 124,
    bio: 'Licensed architect with 10+ years experience.',
    joinedAt: '2023-01-15',
  },
  {
    id: 'd2',
    name: 'Amaka Dike',
    initials: 'AD',
    location: 'Abuja',
    totalDesigns: 22,
    rating: 4.8,
    reviewCount: 87,
    bio: 'Interior design specialist.',
    joinedAt: '2023-03-20',
  },
  {
    id: 'd3',
    name: 'Tunde Koleoso',
    initials: 'TK',
    location: 'Lagos',
    totalDesigns: 15,
    rating: 4.7,
    reviewCount: 43,
    bio: 'Contemporary design expert.',
    joinedAt: '2023-06-10',
  },
  {
    id: 'd4',
    name: 'Ngozi Festus',
    initials: 'NF',
    location: 'Port Harcourt',
    totalDesigns: 29,
    rating: 4.8,
    reviewCount: 65,
    bio: 'Urban design specialist.',
    joinedAt: '2022-11-05',
  },
];

export const DESIGNS: Design[] = [
  {
    id: '1',
    title: 'Modern 4-bedroom duplex',
    description: 'A fully-detailed floor plan for a 4-bedroom duplex.',
    category: 'floor-plan',
    price: 45000,
    licenseType: 'non-exclusive',
    status: 'live',
    fileFormats: ['AutoCAD .dwg', 'PDF'],
    tags: ['4 bedrooms', 'Contemporary', 'Duplex'],
    downloads: 147,
    rating: 4.9,
    reviewCount: 24,
    designer: DESIGNERS[0],
    featured: true,
    specs: {},
    createdAt: '2024-03-10',
    coverImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=300&fit=crop',
  },
  {
    id: '2',
    title: 'Luxury living room concept',
    description: 'A curated interior design concept for a luxury living room.',
    category: 'interior-design',
    price: 28000,
    licenseType: 'non-exclusive',
    status: 'live',
    fileFormats: ['PDF', 'PNG'],
    tags: ['Living room', 'Luxury'],
    downloads: 83,
    rating: 4.8,
    reviewCount: 19,
    designer: DESIGNERS[1],
    featured: true,
    specs: {},
    createdAt: '2024-04-02',
    coverImage: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=400&h=300&fit=crop',
  },
  {
    id: '3',
    title: 'Contemporary bungalow facade',
    description: 'High-quality 3D exterior render.',
    category: '3d-render',
    price: 62000,
    licenseType: 'exclusive',
    status: 'live',
    fileFormats: ['Blender .blend', 'PNG'],
    tags: ['Bungalow', 'Exterior'],
    downloads: 12,
    rating: 4.6,
    reviewCount: 11,
    designer: DESIGNERS[2],
    featured: true,
    specs: {},
    createdAt: '2024-05-15',
    coverImage: 'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=400&h=300&fit=crop',
  },
  {
    id: '4',
    title: '3-bedroom terrace house plan',
    description: 'A compact and efficient 3-bedroom terrace house plan.',
    category: 'floor-plan',
    price: 18500,
    licenseType: 'non-exclusive',
    status: 'live',
    fileFormats: ['AutoCAD .dwg', 'PDF'],
    tags: ['3 bedrooms', 'Terrace'],
    downloads: 34,
    rating: 4.7,
    reviewCount: 9,
    designer: DESIGNERS[3],
    featured: true,
    specs: {},
    createdAt: '2024-06-01',
    coverImage: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=400&h=300&fit=crop',
  },
  {
    id: '5',
    title: 'Minimalist office space',
    description: 'Modern open-plan office design.',
    category: 'commercial',
    price: 55000,
    licenseType: 'non-exclusive',
    status: 'live',
    fileFormats: ['AutoCAD .dwg', 'PDF'],
    tags: ['Office', 'Minimalist'],
    downloads: 56,
    rating: 4.7,
    reviewCount: 14,
    designer: DESIGNERS[0],
    featured: false,
    specs: {},
    createdAt: '2024-06-15',
    coverImage: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=400&h=300&fit=crop',
  },
  {
    id: '6',
    title: 'Modern kitchen design',
    description: 'Contemporary kitchen with island.',
    category: 'interior-design',
    price: 32000,
    licenseType: 'non-exclusive',
    status: 'live',
    fileFormats: ['PDF', 'PNG'],
    tags: ['Kitchen', 'Modern'],
    downloads: 92,
    rating: 4.9,
    reviewCount: 21,
    designer: DESIGNERS[1],
    featured: false,
    specs: {},
    createdAt: '2024-06-20',
    coverImage: 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=400&h=300&fit=crop',
  },
  {
    id: '7',
    title: 'Luxury apartment render',
    description: 'High-end apartment 3D visualization.',
    category: '3d-render',
    price: 78000,
    licenseType: 'exclusive',
    status: 'live',
    fileFormats: ['Blender .blend', 'PNG'],
    tags: ['Apartment', 'Luxury'],
    downloads: 8,
    rating: 4.8,
    reviewCount: 7,
    designer: DESIGNERS[2],
    featured: false,
    specs: {},
    createdAt: '2024-07-01',
    coverImage: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=400&h=300&fit=crop',
  },
  {
    id: '8',
    title: 'Residential building plan',
    description: 'Complete residential building plans.',
    category: 'floor-plan',
    price: 42000,
    licenseType: 'non-exclusive',
    status: 'live',
    fileFormats: ['AutoCAD .dwg', 'PDF'],
    tags: ['Residential', 'Building'],
    downloads: 45,
    rating: 4.7,
    reviewCount: 12,
    designer: DESIGNERS[3],
    featured: false,
    specs: {},
    createdAt: '2024-07-10',
    coverImage: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=400&h=300&fit=crop',
  },
  {
    id: '9',
    title: 'Spa and wellness center',
    description: 'Relaxing spa interior design.',
    category: 'interior-design',
    price: 38000,
    licenseType: 'non-exclusive',
    status: 'live',
    fileFormats: ['PDF', 'PNG'],
    tags: ['Spa', 'Wellness'],
    downloads: 67,
    rating: 4.8,
    reviewCount: 16,
    designer: DESIGNERS[1],
    featured: false,
    specs: {},
    createdAt: '2024-07-15',
    coverImage: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400&h=300&fit=crop',
  },
  {
    id: '10',
    title: 'Modern villa exterior',
    description: 'Stunning modern villa 3D render.',
    category: 'exterior',
    price: 85000,
    licenseType: 'exclusive',
    status: 'live',
    fileFormats: ['Blender .blend', 'PNG'],
    tags: ['Villa', 'Modern'],
    downloads: 23,
    rating: 4.9,
    reviewCount: 18,
    designer: DESIGNERS[0],
    featured: false,
    specs: {},
    createdAt: '2024-07-20',
    coverImage: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=400&h=300&fit=crop',
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  all: 'All',
  'floor-plan': 'Floor plans',
  'interior-design': 'Interior design',
  '3d-render': '3D renders',
  exterior: 'Exterior',
  commercial: 'Commercial',
  'bim-cad': 'BIM / CAD files',
};
