import type { Design, Designer } from '@/types';

export const DESIGNERS: Designer[] = [
  {
    id: 'd1',
    name: 'Chukwudi Adesanya',
    initials: 'CA',
    location: 'Lagos',
    totalDesigns: 38,
    rating: 4.9,
    reviewCount: 124,
    bio: 'Licensed architect with 10+ years designing residential and commercial spaces across Nigeria.',
    joinedAt: '2023-01-15',
  },
  {
    id: 'd2',
    name: 'Amaka Dike',
    initials: 'AD',
    location: 'Abuja',
    totalDesigns: 22,
    rating: 4.8,
    reviewCount: 87,
    bio: 'Interior design specialist focused on luxury residential projects.',
    joinedAt: '2023-03-20',
  },
  {
    id: 'd3',
    name: 'Tunde Koleoso',
    initials: 'TK',
    location: 'Lagos',
    totalDesigns: 15,
    rating: 4.6,
    reviewCount: 43,
    bio: 'Specialises in contemporary bungalows and mid-rise residential buildings.',
    joinedAt: '2023-06-10',
  },
  {
    id: 'd4',
    name: 'Ngozi Festus',
    initials: 'NF',
    location: 'Port Harcourt',
    totalDesigns: 29,
    rating: 4.7,
    reviewCount: 65,
    bio: 'Architect and interior designer specialising in compact urban homes.',
    joinedAt: '2022-11-05',
  },
];

export const DESIGNS: Design[] = [
  {
    id: '1',
    title: 'Modern 4-bedroom duplex',
    description:
      'A fully-detailed floor plan for a 4-bedroom duplex optimised for Nigerian plot sizes. Includes ground and first floor layouts, room dimensions, and structural annotations. Suitable for residential developers and self-build projects.',
    category: 'floor-plan',
    price: 45000,
    licenseType: 'non-exclusive',
    status: 'live',
    fileFormats: ['AutoCAD .dwg', 'PDF', 'PNG'],
    tags: ['4 bedrooms', 'Lagos style', 'Contemporary', 'Duplex'],
    downloads: 147,
    rating: 4.9,
    reviewCount: 24,
    designer: DESIGNERS[0],
    featured: true,
    specs: {
      'File formats': 'AutoCAD .dwg, PDF, PNG',
      'Plot size': '600 sqm (approx.)',
      Floors: 'Ground + First',
      License: 'Non-exclusive personal use',
    },
    createdAt: '2024-03-10',
  },
  {
    id: '2',
    title: 'Luxury living room concept',
    description:
      'A curated interior design concept for a luxury living room featuring contemporary Nigerian aesthetics. Includes mood boards, material palette, and furniture layout.',
    category: 'interior-design',
    price: 28000,
    licenseType: 'non-exclusive',
    status: 'live',
    fileFormats: ['PDF', 'PNG', 'SketchUp .skp'],
    tags: ['Living room', 'Luxury', 'Contemporary', 'Mood board'],
    downloads: 83,
    rating: 4.8,
    reviewCount: 19,
    designer: DESIGNERS[1],
    featured: true,
    specs: {
      'File formats': 'PDF, PNG, SketchUp .skp',
      Rooms: 'Living room',
      Includes: 'Mood board, material palette, furniture layout',
      License: 'Non-exclusive personal use',
    },
    createdAt: '2024-04-02',
  },
  {
    id: '3',
    title: 'Contemporary bungalow facade',
    description:
      'High-quality 3D exterior render of a contemporary single-storey bungalow. Includes front, side, and rear elevations with landscaping.',
    category: '3d-render',
    price: 62000,
    licenseType: 'exclusive',
    status: 'live',
    fileFormats: ['Blender .blend', 'PNG (4K)', 'PDF'],
    tags: ['Bungalow', 'Exterior', '3D render', 'Landscaping'],
    downloads: 12,
    rating: 4.6,
    reviewCount: 11,
    designer: DESIGNERS[2],
    featured: true,
    specs: {
      'File formats': 'Blender .blend, PNG (4K), PDF',
      Views: 'Front, Side, Rear',
      Resolution: '4K (3840×2160)',
      License: 'Exclusive — single buyer',
    },
    createdAt: '2024-05-15',
  },
  {
    id: '4',
    title: '3-bedroom terrace house plan',
    description:
      'A compact and efficient 3-bedroom terrace house plan ideal for urban plots. Clean room layouts with natural light prioritised throughout.',
    category: 'floor-plan',
    price: 18500,
    licenseType: 'non-exclusive',
    status: 'live',
    fileFormats: ['AutoCAD .dwg', 'PDF'],
    tags: ['3 bedrooms', 'Terrace', 'Urban', 'Compact'],
    downloads: 34,
    rating: 4.7,
    reviewCount: 9,
    designer: DESIGNERS[3],
    featured: true,
    specs: {
      'File formats': 'AutoCAD .dwg, PDF',
      'Plot size': '300 sqm (approx.)',
      Floors: 'Ground only',
      License: 'Non-exclusive personal use',
    },
    createdAt: '2024-06-01',
  },
  {
    id: '5',
    title: 'Open-plan office layout',
    description:
      'Modern open-plan office design for 30-50 staff. Includes workstation zones, meeting rooms, breakout areas, and reception.',
    category: 'commercial',
    price: 75000,
    licenseType: 'non-exclusive',
    status: 'live',
    fileFormats: ['AutoCAD .dwg', 'Revit .rvt', 'PDF'],
    tags: ['Office', 'Commercial', 'Open plan', 'Corporate'],
    downloads: 28,
    rating: 4.8,
    reviewCount: 15,
    designer: DESIGNERS[0],
    featured: false,
    specs: {
      'File formats': 'AutoCAD .dwg, Revit .rvt, PDF',
      Capacity: '30-50 staff',
      Zones: 'Workstation, meeting, breakout, reception',
      License: 'Non-exclusive commercial use',
    },
    createdAt: '2024-04-20',
  },
  {
    id: '6',
    title: 'Nigerian kitchen redesign pack',
    description:
      'Full kitchen interior design pack with layout options, cabinet elevations, and material specifications tailored for Nigerian homes.',
    category: 'interior-design',
    price: 22000,
    licenseType: 'non-exclusive',
    status: 'live',
    fileFormats: ['PDF', 'PNG'],
    tags: ['Kitchen', 'Interior', 'Nigerian home', 'Cabinet design'],
    downloads: 56,
    rating: 4.5,
    reviewCount: 22,
    designer: DESIGNERS[1],
    featured: false,
    specs: {
      'File formats': 'PDF, PNG',
      Rooms: 'Kitchen',
      Includes: 'Layout options, cabinet elevations, material specs',
      License: 'Non-exclusive personal use',
    },
    createdAt: '2024-05-01',
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  all: 'All',
  'floor-plan': 'Floor plans',
  'interior-design': 'Interior design',
  '3d-render': '3D renders',
  exterior: 'Exterior',
  commercial: 'Commercial',
  'bim-cad': 'BIM / CAD files',
};